insert into [sql_nome_estabelecimento].[dbo].[mensagens] select * from [delivery].[dbo].[mensagens] GO
insert into [sql_nome_estabelecimento].[dbo].[tipo] select * from [delivery].[dbo].[tipo] GO
insert into [sql_nome_estabelecimento].[dbo].[endereco] select * from [delivery].[dbo].[endereco] GO
insert into [sql_nome_estabelecimento].[dbo].[retirada] select * from [delivery].[dbo].[retirada] GO
insert into [sql_nome_estabelecimento].[dbo].[pessoa] select * from [delivery].[dbo].[pessoa] GO
insert into [sql_nome_estabelecimento].[dbo].[pagamento] select * from [delivery].[dbo].[pagamento] GO
insert into [sql_nome_estabelecimento].[dbo].[horario] select * from [delivery].[dbo].[horario] GO
insert into [sql_nome_estabelecimento].[dbo].[status_da_compra] select * from [delivery].[dbo].[status_da_compra] GO
insert into [sql_nome_estabelecimento].[dbo].[complemento] select * from [delivery].[dbo].[complemento] GO
insert into [sql_nome_estabelecimento].[dbo].[pontos] select * from [delivery].[dbo].[pontos] GO
insert into [sql_nome_estabelecimento].[dbo].[resgate] select * from [delivery].[dbo].[resgate] GO
insert into [sql_nome_estabelecimento].[dbo].[pedido] select * from [delivery].[dbo].[pedido] GO
insert into [sql_nome_estabelecimento].[dbo].[grupo_do_pagamento] select * from [delivery].[dbo].[grupo_do_pagamento] GO
insert into [sql_nome_estabelecimento].[dbo].[acesso] select * from [delivery].[dbo].[acesso] GO
insert into [sql_nome_estabelecimento].[dbo].[biblioteca_de_palavra] select * from [delivery].[dbo].[biblioteca_de_palavra] GO
insert into [sql_nome_estabelecimento].[dbo].[bandeira] select * from [delivery].[dbo].[bandeira] GO
insert into [sql_nome_estabelecimento].[dbo].[perfil] select * from [delivery].[dbo].[perfil] GO
insert into [sql_nome_estabelecimento].[dbo].[produto] select * from [delivery].[dbo].[produto] GO
insert into [sql_nome_estabelecimento].[dbo].[status_pessoa] select * from [delivery].[dbo].[status_pessoa] GO
insert into [sql_nome_estabelecimento].[dbo].[sysdiagrams] select * from [delivery].[dbo].[sysdiagrams] GO
insert into [sql_nome_estabelecimento].[dbo].[filial] select * from [delivery].[dbo].[filial] GO
insert into [sql_nome_estabelecimento].[dbo].[compra] select * from [delivery].[dbo].[compra] GO
insert into [sql_nome_estabelecimento].[dbo].[montagem] select * from [delivery].[dbo].[montagem] GO
insert into [sql_nome_estabelecimento].[dbo].[estoque] select * from [delivery].[dbo].[estoque] GO
insert into [sql_nome_estabelecimento].[dbo].[desconto] select * from [delivery].[dbo].[desconto] GO
insert into [sql_nome_estabelecimento].[dbo].[oferta] select * from [delivery].[dbo].[oferta] GO
insert into [sql_nome_estabelecimento].[dbo].[agenda] select * from [delivery].[dbo].[agenda] GO