//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class assinatura
    {
        public int id { get; set; }
        public Nullable<int> pessoa_id { get; set; }
        public Nullable<int> item_id { get; set; }
        public string codigo { get; set; }
        public Nullable<decimal> valor { get; set; }
    
        public virtual item item { get; set; }
        public virtual pessoa pessoa { get; set; }
    }
}
