//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cartao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cartao()
        {
            this.compra1 = new HashSet<compra>();
        }
    
        public int id { get; set; }
        public string numero { get; set; }
        public string nome { get; set; }
        public string expiracao { get; set; }
        public string cvv { get; set; }
        public string hash { get; set; }
        public Nullable<int> pessoa_id { get; set; }
        public string documento { get; set; }
        public string pagarme_id { get; set; }
        public string bandeira { get; set; }
        public Nullable<long> place_id { get; set; }
        public Nullable<int> compra_id { get; set; }
        public Nullable<bool> credito { get; set; }
        public Nullable<bool> debito { get; set; }
    
        public virtual compra compra { get; set; }
        public virtual pessoa pessoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<compra> compra1 { get; set; }
    }
}
