//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class compra_item
    {
        public int id { get; set; }
        public Nullable<int> item_id { get; set; }
        public Nullable<int> compra_id { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> quantidade { get; set; }
    
        public virtual compra compra { get; set; }
        public virtual item item { get; set; }
    }
}
