//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ec2 : DbContext
    {
        public ec2()
            : base("name=ec2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<acesso> acesso { get; set; }
        public virtual DbSet<assinatura> assinatura { get; set; }
        public virtual DbSet<biblioteca_de_palavra> biblioteca_de_palavra { get; set; }
        public virtual DbSet<cartao> cartao { get; set; }
        public virtual DbSet<compra> compra { get; set; }
        public virtual DbSet<compra_item> compra_item { get; set; }
        public virtual DbSet<grupo> grupo { get; set; }
        public virtual DbSet<grupo_item> grupo_item { get; set; }
        public virtual DbSet<grupo_pessoa> grupo_pessoa { get; set; }
        public virtual DbSet<item> item { get; set; }
        public virtual DbSet<localizacao> localizacao { get; set; }
        public virtual DbSet<localizacao_pessoa> localizacao_pessoa { get; set; }
        public virtual DbSet<notificacao> notificacao { get; set; }
        public virtual DbSet<padrinho> padrinho { get; set; }
        public virtual DbSet<pagamento> pagamento { get; set; }
        public virtual DbSet<perfil> perfil { get; set; }
        public virtual DbSet<pessoa> pessoa { get; set; }
        public virtual DbSet<rastreador> rastreador { get; set; }
        public virtual DbSet<responsavel_juridico> responsavel_juridico { get; set; }
        public virtual DbSet<status_da_compra> status_da_compra { get; set; }
        public virtual DbSet<status_usuario> status_usuario { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tipo> tipo { get; set; }
        public virtual DbSet<transacao> transacao { get; set; }
    }
}
