//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupo_pessoa
    {
        public int id { get; set; }
        public Nullable<int> pessoa_id { get; set; }
        public Nullable<int> grupo_id { get; set; }
        public Nullable<bool> ativo { get; set; }
        public Nullable<int> convite { get; set; }
    
        public virtual grupo grupo { get; set; }
        public virtual pessoa pessoa { get; set; }
    }
}
