//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public item()
        {
            this.assinatura = new HashSet<assinatura>();
            this.compra_item = new HashSet<compra_item>();
            this.grupo_item = new HashSet<grupo_item>();
            this.localizacao = new HashSet<localizacao>();
            this.padrinho = new HashSet<padrinho>();
            this.rastreador = new HashSet<rastreador>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public string cor { get; set; }
        public string raca { get; set; }
        public byte[] photo { get; set; }
        public string photo_itype { get; set; }
        public string sangue { get; set; }
        public Nullable<System.DateTime> nascimento { get; set; }
        public string pelo { get; set; }
        public string vacinas { get; set; }
        public Nullable<int> responsavel_id { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<int> tipo_id { get; set; }
        public string cnpj { get; set; }
        public string cpf { get; set; }
        public Nullable<bool> ativo { get; set; }
        public Nullable<int> rastreado_id { get; set; }
        public string descricao { get; set; }
        public Nullable<bool> perdido { get; set; }
        public string genero { get; set; }
        public string rg { get; set; }
        public Nullable<int> estoque { get; set; }
        public Nullable<bool> doacao { get; set; }
        public Nullable<bool> apadrinhar { get; set; }
        public string modelo { get; set; }
        public string fabricante { get; set; }
        public string marca { get; set; }
        public string num_serie { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assinatura> assinatura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<compra_item> compra_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<grupo_item> grupo_item { get; set; }
        public virtual pessoa pessoa { get; set; }
        public virtual pessoa pessoa1 { get; set; }
        public virtual tipo tipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<localizacao> localizacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<padrinho> padrinho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rastreador> rastreador { get; set; }
    }
}
