//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class localizacao
    {
        public int id { get; set; }
        public Nullable<int> item_id { get; set; }
        public Nullable<decimal> lat { get; set; }
        public Nullable<decimal> lng { get; set; }
        public Nullable<System.DateTime> cadastro { get; set; }
        public byte[] photo { get; set; }
        public string photo_itype { get; set; }
        public string descricao { get; set; }
        public Nullable<bool> ativo { get; set; }
    
        public virtual item item { get; set; }
    }
}
