//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class padrinho
    {
        public int id { get; set; }
        public Nullable<int> padrinho_id { get; set; }
        public Nullable<int> item_id { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<System.DateTime> cadastro { get; set; }
    
        public virtual item item { get; set; }
        public virtual pessoa pessoa { get; set; }
    }
}
