//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pessoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pessoa()
        {
            this.assinatura = new HashSet<assinatura>();
            this.cartao = new HashSet<cartao>();
            this.compra = new HashSet<compra>();
            this.compra1 = new HashSet<compra>();
            this.grupo_pessoa = new HashSet<grupo_pessoa>();
            this.item = new HashSet<item>();
            this.item1 = new HashSet<item>();
            this.localizacao_pessoa = new HashSet<localizacao_pessoa>();
            this.notificacao = new HashSet<notificacao>();
            this.padrinho = new HashSet<padrinho>();
            this.responsavel_juridico = new HashSet<responsavel_juridico>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string facebook { get; set; }
        public string cpf { get; set; }
        public string rg { get; set; }
        public Nullable<int> perfil_id { get; set; }
        public string phone { get; set; }
        public string phone_optional { get; set; }
        public string mobile { get; set; }
        public string mobile_optional { get; set; }
        public Nullable<int> rating { get; set; }
        public string password { get; set; }
        public byte[] photo { get; set; }
        public string description { get; set; }
        public Nullable<bool> active { get; set; }
        public string charge { get; set; }
        public Nullable<System.DateTime> email_change { get; set; }
        public Nullable<int> status_usuario_id { get; set; }
        public string photo_itype { get; set; }
        public string push_id { get; set; }
        public string push_arn { get; set; }
        public Nullable<decimal> credit { get; set; }
        public string cnpj { get; set; }
        public string razao_social { get; set; }
        public Nullable<long> place_id { get; set; }
        public string Agencia { get; set; }
        public string AgenciaDv { get; set; }
        public string Conta { get; set; }
        public string ContaDv { get; set; }
        public string BankCode { get; set; }
        public string DocumentNumber { get; set; }
        public string LegalName { get; set; }
        public Nullable<decimal> comissao { get; set; }
        public string pagarme_id { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<int> external_id { get; set; }
        public Nullable<int> filial_id { get; set; }
        public byte[] cpf_image { get; set; }
        public string cpf_image_itype { get; set; }
        public byte[] rg_image { get; set; }
        public string rg_image_itype { get; set; }
        public byte[] comprovante { get; set; }
        public string comprovante_itype { get; set; }
        public Nullable<bool> genero { get; set; }
        public byte[] antecedentes { get; set; }
        public string antecedentes_itype { get; set; }
        public byte[] certificado { get; set; }
        public string certificado_itype { get; set; }
        public string BankToken { get; set; }
        public Nullable<int> especialidade_id { get; set; }
        public Nullable<decimal> lat { get; set; }
        public Nullable<decimal> lng { get; set; }
        public string rua { get; set; }
        public string numero { get; set; }
        public string complemento { get; set; }
        public string cidade { get; set; }
        public string pais { get; set; }
        public string cep { get; set; }
        public string bairro { get; set; }
        public string estado { get; set; }
        public string grupo { get; set; }
        public string filial { get; set; }
        public string franqueador { get; set; }
        public string franqueado { get; set; }
        public Nullable<decimal> lat_celular { get; set; }
        public Nullable<decimal> lon_celular { get; set; }
        public Nullable<System.DateTime> data_localizacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assinatura> assinatura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cartao> cartao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<compra> compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<compra> compra1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<grupo_pessoa> grupo_pessoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<item> item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<item> item1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<localizacao_pessoa> localizacao_pessoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notificacao> notificacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<padrinho> padrinho { get; set; }
        public virtual perfil perfil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<responsavel_juridico> responsavel_juridico { get; set; }
        public virtual status_usuario status_usuario { get; set; }
    }
}
