//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class responsavel_juridico
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string rg { get; set; }
        public string cpf { get; set; }
        public string email { get; set; }
        public string celular { get; set; }
        public string telefone { get; set; }
        public Nullable<int> porcentagem { get; set; }
        public string cargo_posicao { get; set; }
        public Nullable<int> pessoa_id { get; set; }
        public Nullable<int> tipo_acesso { get; set; }
        public string senha { get; set; }
    
        public virtual pessoa pessoa { get; set; }
    }
}
